= 💤 LazyVim Configuration
:toc:
:toc-placement!:
:toc-title: 
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

This repoistory contains the configs and files needed to build a custom `nvim` container ready to act as a fully featured text editor out of the box.

toc::[]


== References 

https://github.com/LazyVim/starer::
   This repo is a fork of this standard template for a LazyVim configuration.
https://lazyvim.github.io/installation::
   Documentation where to go once you've cloned the base config repo 
https://www.youtube.com/watch?v=N93cTbtLCIM["Configuration Walkthrough Video"]::
   Confguration discussion w ttps://github.com/elijahmanor["@elijahmanor"] walkingthrough the deployment and use of the LazyVim/starter` repo

== Usage


=== Manual

To build and push the images:


  $ export IMAGE_TAG=github.com/kriipke/nvim:0.1.5
  $ docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t $IMAGE_TAG  . --load
  $ docker push $IMAGE_TAG 


=== I a rollout/deployment

    name: ci
    
    on:
      push:
    
    jobs:
      buildx:
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v4
          -
            # Add support for more platforms with QEMU (optional)
            # https://github.com/docker/setup-qemu-action
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
            with:
              platforms: linux/amd64, linux/arm64 #linux/arm/v7

    

## Repository Structure

### `/lua/lazyvim/config/lazy.lua`      
### `/lua/lazyvim/config/options.lua`      
### `/lua/lazyvim/config/`      
__**`:h LazyVim-configuration`**__

The files under `config` will be automatically loaded at the appropriate time, so you don’t need to require those files manually. 

Immutable set of configs shiped by LazyVim that are sourced prior to any user configs. Those are sourced after out of `/lua/plugins/`.

### `/lua/plugins/`
`:h LazyVim-configuration`
